containers:
- name: DevOpsProject
  image: serve
  ports:
  - containerPort: 3000
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"